### ISSUE TITLE
Should `raw` include common indentation?

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-string-dedent#26]
```js
(t => t.raw[0].includes("  "))```
  indented``` // true, or false?
```

**Comment by theScottyJam** [comment]
I would hope that returns false. There's no reason for a template tag to need access to the original indentation if you're explicitly used the tripple quote in an attempt to remove indentation. It would make for some really weird and non-intuitive behaviour if a tag utilized the original indentation that you explicitly wanted ignored. Plus, it may be backwards incompatible if it returned true - template tags that compare `.raw` with the non-raw data may start to fail if they weren't designed to handle the case where `.raw` contains indentation and the non-raw data does not.

**Comment by Jamesernator** [comment]
If it is desirable I agree with @theScottyJam that changing the existing `.raw` shouldn't happen as it might be passed to other libraries, although if there were use cases for dedent-aware libraries it could be exposed as another property (`t.rawIndented`?). Dunno what the use cases would be though.

**Comment by jridgewell** [comment]
I also think this should return false (`raw` array should be dedented just like cooked).

To me (and this is certainly debatable) the raw array is intended to return the non-interpreted chars (eg, raw should contain `\u{0061}` instead of `a` if that's what is written). The indentation isn't quite the same since it's not being interpreted (someone give me a better word for this), and the dev is explicitly asking us to remove it.
